import img  from '../img/01.jpg'

export default function Banner(){
    


    return`

   
     <img class="container-banner-img"src="${img}" style="" alt="" >
     <div style="position: absolute; top: 400px; left: 0; right: 0;">
     <div class="container-banner-button">
     <button class="banner-button">◄</button>
     <button class="banner-button">►</button></button>
    </div>
    </div>
    
    
    
    `
}